Added addons socials
Compliance-Resource-Pack/Website pull request #47
Opened 2022-01-26 20:18 UTC by TheRolfFR

Made simple social icons,

![image](https://user-images.githubusercontent.com/18086786/151240144-3b0212af-867f-4432-bd2b-e50b2b986ef7.png)

Code is here, may need more style tuning in main.css

2022-01-26 22:13 UTC, RobertRR11 commented
Either I'm doing something very wrong or it doesn't seem to work?
![image](https://user-images.githubusercontent.com/57044042/151255737-f6c5efbd-bef9-4174-8186-45ca4aa3a965.png)

2022-01-26 22:18 UTC, Juknum commented
> Either I'm doing something very wrong or it doesn't seem to work? ![image](https://user-images.githubusercontent.com/57044042/151255737-f6c5efbd-bef9-4174-8186-45ca4aa3a965.png)

Can confirm, doesn't seems to be working on my side either

2022-01-26 22:22 UTC, RobertRR11 commented
> Either I'm doing something very wrong or it doesn't seem to work?

Also wanted to add that there are no relevant errors in console (only disqus errors because of locally hosting the site)

2022-01-26 22:28 UTC, RobertRR11 commented
Actually just noticed that it was because one of my uBlock Origin blocklists that removes social links. But there are still some issues:
1. Only shows up when there are multiple authors
2. Authors with no social links have an empty spot at the bottom
3. A massive gap when there are social links

![image](https://user-images.githubusercontent.com/57044042/151257390-c988a244-bdc8-46d2-b0de-50e6a6b097f1.png)

2022-01-26 22:30 UTC, Juknum requested changes

2022-01-26 22:30 UTC, Juknum commented on js/addons/addon-post.js
> +                  </div>
This somewhat never show inside the page 🤔

2022-01-26 22:31 UTC, Juknum commented
> Actually just noticed that it was because one of my uBlock Origin blocklists that removes social links.
Is there a way to avoid uBlock Origin to block those links?

2022-01-26 22:33 UTC, RobertRR11 commented
> > Actually just noticed that it was because one of my uBlock Origin blocklists that removes social links.
> 
> Is there a way to avoid uBlock Origin blocking those links?

It's not being blocked by default, it's a special blocklist that needs to be activated manually.

2022-01-27 08:47 UTC, TheRolfFR commented
So @RobertRR11 you shouldn't use the class for the icons because the class versions use the main css file from fontawesome. What I did in order to optimize speed on my website was getting rid of it and just imported the solid and brands styles with only the fonts. Much much lighter and reduces considerably the loading time.

2022-01-27 08:48 UTC, TheRolfFR commented
Made it work with one author so you get this :
![image](https://user-images.githubusercontent.com/18086786/151323847-cc76cb24-a668-4b98-bf0b-f610b545cab4.png)

When I said icons may be tuning it was maybe make them all white in order to have a consistent look and alignment

2022-01-27 12:57 UTC, Juknum commented
Seems good, but they aren't aligned on the y axis and this confuse me a lot xd

2022-01-27 17:18 UTC, RobertRR11 commented
Now everything looks good to me, but the last issue I see is that the paypal links for some reason also include the link of the hosted site
![image](https://user-images.githubusercontent.com/57044042/151409969-1da5ce29-1965-4459-9408-4fa3fbd71d94.png)

2022-01-28 18:11 UTC, RobertRR11 commented
> Now everything looks good to me, but the last issue I see is that the paypal links for some reason also include the link of the hosted site

Hey @TheRolfFR this is basically the last issue, can you look into it?

2022-01-28 19:21 UTC, TheRolfFR commented
> Hey @TheRolfFR this is basically the last issue, can you look into it?

Just some missing http on the urls, simple fix on 27bd622
![image](https://user-images.githubusercontent.com/18086786/151608027-64e10124-ef2a-44ff-8550-7a5c93b5e4b6.png)
_Example at ``/addons/gilded-ores``_

2022-01-28 20:17 UTC, RobertRR11 approved these changes

2022-01-28 20:53 UTC, merged